version = 0.1

[default.deploy.parameters]
stack_name = "aialpha-sam-comprehend-61"
resolve_s3 = true
s3_prefix = "aialpha-sam-comprehend-61"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"kandidat-61-data\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
