name: Build & Push Docker image
on:
  push:
    branches: 
      - main
    paths:
      - 'sentiment-docker/**'
      - '.github/workflows/docker-build.yml' 
  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        id: meta
        run: echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/sentiment-docker" >> $GITHUB_OUTPUT

      - name: Build
        run: docker build -t ${{ steps.meta.outputs.IMAGE }}:latest sentiment-docker

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push latest
        run: docker push ${{ steps.meta.outputs.IMAGE }}:latest

      - name: Push commit tag
        run: |
          TAG=sha-${GITHUB_SHA::7}
          docker tag ${{ steps.meta.outputs.IMAGE }}:latest ${{ steps.meta.outputs.IMAGE }}:${TAG}
          docker push ${{ steps.meta.outputs.IMAGE }}:${TAG}
