name: Terraform S3 Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra-s3/**'
      - '.github/workflows/terraform-s3.yml'
  pull_request:
    paths:
      - 'infra-s3/**'
      - '.github/workflows/terraform-s3.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (PR only)
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false

      - name: Terraform Apply (main branch)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        
